########################################################
### EMBEDDED SERVER CONFIGURATION (ServerProperties) ###
########################################################
server:
  port: 8791
  session:
    timeout: 28800

##############
### SPRING ###
##############
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    schema: classpath:/mysql.sql
    url: jdbc:mariadb://10.31.40.4:3306/mifan_trace?useUnicode=true&autoReconnect=true
    username: '{cipher}ee0f47d79c7962d74bf05e5227c7d85c8b68cba4dadc25bdf41e1a0196a4a27c'
    password: '{cipher}d2d4229be8bd6ee1b5b525aaaa379afadd194fcad6dfc75efe73bf7762574c80'
    max-active: 1000
    max-idle: 8
    min-idle: 1
    initial-size: 10
    validation-query=: SELECT 'x' FROM DUAL
    test-on-borrow: true
    test-on-return: false
    test-while-idle: true
    time-between-eviction-runs-millis: 3000
    min-evictable-idle-time-millis: 30000
    max-wait: 60000
    # Switch this on to create the schema on startup:
    initialize: false
    continueOnError: true
  rabbitmq:
    host: 10.31.236.67
    port: 5672
    username: '{cipher}52fe7636edaffe0c51b2ca260242dd893e42b78e7b16fd1b3d47935fae8f2827'
    password: '{cipher}7e476c464747a8e971a943f0dede1ee6cf486be67721e5d1dfcd8748d01db1c9'
  sleuth:
    enabled: false
  output:
    ansi:
      enabled: always

###########################
### SECURITY PROPERTIES ###
###########################
security:
  basic:
    enabled: true
  user:
    name: '{cipher}8f3f803c47eb5f10ed8ef634d368ecc3ffbba9e4f1a8586294aa1b00184dbcd2'
    password: '{cipher}f9621ba1d0b0fec59454052ad379df2703953a9caa7bfb0957af50c570e03cfb'

##############
### ZIPKIN ###
##############
zipkin:
  storage:
    type: mysql